apiVersion: v1
kind: ConfigMap
metadata:
  name: proxy-conf
  namespace: gateway
data:
  nginx.conf: |
    events {}
    http {
      upstream backend {
        # This will be replaced by the CI/CD pipeline with actual LoadBalancer URL
        server BACKEND_LB_URL:8080;
      }
      server {
        listen 80;
        location / {
          proxy_pass http://backend;
        }
      }
    }
